### ISSUE TITLE
In-article widget doesn't show up but invisible div takes up space

### ISSUE THREAD

**Issue by githamm** [denverpost/wordpress-helpers#31]
Code is on page in source view:

`<iframe src="http://extras.denverpost.com/app/in-article-promo/politics-1.html" width="100%" height="100px" scrolling="yes" class="iframe" allowtransparency="1" id="5820d2901d012" ></iframe>`

(Screenshot in slack)

**Comment by freejoe76** [comment]
Talked with @githamm, explained this functionality happens when the promo is promoting the same article as it's on.
